"""User

Revision ID: b631d188273c
Revises: 
Create Date: 2020-06-07 15:10:13.789802

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b631d188273c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('username', sa.String(length=256), nullable=False),
                    sa.Column('email', sa.String(length=256), nullable=False),
                    sa.Column('password_hash', sa.String(length=1024), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
